namespace: kube-system

daemonSet:
  priorityClassName: system-node-critical
  # Use OnDelete for change the plugin strategy
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  # tolerations:
    # add toleration as needed
    # - key: furiosa.ai/npu
    #   operator: Exists
  image:
    repository: ghcr.io/furiosa-ai/furiosa-device-plugin
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    cpu: 100m
    memory: 64Mi
  # locate you image pull secret in your cluster
  imagePullSecrets:
   # - name: imagepullsecret

config:
  resourceStrategy: generic
  debugMode: false
  disabledDeviceUUIDListMap:
   # node:
   #   - "uuid"
