apiVersion: v1
kind: ConfigMap
metadata:
  name: furiosa-device-plugin-config-cm
  namespace: kube-system
data:
  config.yaml: |
    resourceStrategy: generic
    debugMode: false
    disabledDeviceUUIDListMap:
      {}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: furiosa-device-plugin
  namespace: kube-system
  labels:
    helm.sh/chart: furiosa-device-plugin-0.1.0
    app.kubernetes.io/name: furiosa-device-plugin
    app.kubernetes.io/instance: furiosa-device-plugin
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: furiosa-device-plugin
      app.kubernetes.io/instance: furiosa-device-plugin
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: furiosa-device-plugin
        app.kubernetes.io/instance: furiosa-device-plugin
    spec:
      priorityClassName:  system-node-critical
      containers:
        - name: furiosa-device-plugin
          image: registry.corp.furiosa.ai/furiosa/furiosa-device-plugin:latest
          command: ["./main"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "spec.nodeName"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: config
              mountPath: /etc/config
            - name: kubelet-socket
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev-fs
              mountPath: /dev
            - name: sys-fs
              mountPath: /sys
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: feature.node.kubernetes.io/pci-1ed2.present
                    operator: In
                    values:
                      - "true"
      volumes:
        - name: config
          configMap:
            name: furiosa-device-plugin-config-cm
        - name: kubelet-socket
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev-fs
          hostPath:
            path: /dev
        - name: sys-fs
          hostPath:
            path: /sys
