apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "furiosa-device-plugin.name" . }}-config-cm
  namespace: {{ .Values.namespace | default "kube-system" }}
data:
  config.yaml: |
    resourceStrategy: {{ .Values.globalConfig.resourceStrategyMap.warboy | default "generic" }}
    debugMode: {{ .Values.globalConfig.debugMode | default "false" }}
