apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "furiosa-device-plugin.name" . }}
  namespace: {{ .Values.namespace | default "kube-system" }}
  labels:
    {{- include "furiosa-device-plugin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "furiosa-device-plugin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "furiosa-device-plugin.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      priorityClassName:  {{ .Values.daemonSet.priorityClassName | default "system-node-critical" }}
      containers:
        - name: {{ include "furiosa-device-plugin.name" . }}
          image: {{ .Values.daemonSet.image.repository | default "ghcr.io/furiosa-ai/furiosa-device-plugin" }}:{{ .Values.daemonSet.image.tag | default "latest" }}
          command: ["./main"]
          {{- if .Values.localConfig }}
          args: ["--localConfigPath={{ .Values.localConfig.localConfigDir }}/{{ .Values.localConfig.localConfigFile }}"]
          {{- end }}
          imagePullPolicy: {{ .Values.daemonSet.image.pullPolicy | default "IfNotPresent" }}
          resources:
            requests:
              cpu: {{ .Values.daemonSet.resources.cpu | default "100m" }}
              memory: {{ .Values.daemonSet.resources.memory | default "64Mi" }}
            limits:
              cpu: {{ .Values.daemonSet.resources.cpu | default "100m" }}
              memory: {{ .Values.daemonSet.resources.memory | default "64Mi" }}
          volumeMounts:
            - name: global-config
              mountPath: /etc/config/global_config.yaml
              subPath: global
            {{- if .Values.localConfig }}
            - name: local-config
              mountPath: {{ .Values.localConfig.localConfigDir }}
            {{- end }}
            - name: kubelet-socket
              mountPath: /var/lib/kubelet/device-plugins
            - name: dev-fs
              mountPath: /dev
            - name: sys-fs
              mountPath: /sys
      volumes:
        - name: global-config
          configMap:
            name: {{ include "furiosa-device-plugin.name" . }}-global-config-cm
        {{- if .Values.localConfig }}
        - name: local-config
          hostPath:
            path: {{ .Values.localConfig.localConfigDir }}
        {{- end }}
        - name: kubelet-socket
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev-fs
          hostPath:
            path: /dev
        - name: sys-fs
          hostPath:
            path: /sys
