name: Build & Push new container image for new release

on:
  push:
    branches:
      - releases/**

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@v13
        with:
          image_name: ${{ github.repository }}
          image_tag: ${{ github.event.release.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}